### ISSUE TITLE
is 4.0.0 stable?

### ISSUE THREAD

**Issue by sanderpick** [chiru-labs/ERC721A-Upgradeable#10]
sorry for the question as an "issue", but didn't see another venue for such things. are you planning on publishing 4.0.0 to npm, or should i wait for 4.0.1?

cheers and thanks for your efforts!

**Comment by Vectorized** [comment]
Thanks for the catch!
The previous publishing attempt did not pass.

We have just published 4.0.0 to npm. 
4.0.0 will be stable.
