### ISSUE TITLE
Cyclic dependencies in ERC721AUpgradeable.sol and ERC721AStorage.sol

### ISSUE THREAD

**Issue by jovijovi** [chiru-labs/ERC721A-Upgradeable#14]
- Issue: Cyclic dependencies in `ERC721AUpgradeable.sol` and `ERC721AStorage.sol` cause Hardhat flatten error.
- Error Message:
  ```text
  Error HH603: Hardhat flatten doesn't support cyclic dependencies.
  For more info go to https://hardhat.org/HH603 or run Hardhat with --show-stack-traces
  ```
- Version: `4.2.0`
- Cyclic Dependencies Code:
  - `ERC721AUpgradeable.sol` line 8

    ```solidity
    import {ERC721AStorage} from './ERC721AStorage.sol';
    ```

  - `ERC721AStorage.sol` line 5

    ```solidity
    import {ERC721AUpgradeable} from './ERC721AUpgradeable.sol';
    ```

Is this code dependency approach intentional?
Thank you :D

**Comment by Vectorized** [comment]
The is caused by the transpiler importing ERC721A for the struct, which was introduced to patch a compiler bug.

I will make a fix shortly.
