### ISSUE TITLE
Missing onlyInitializing modifer

### ISSUE THREAD

**Issue by gmspacex** [chiru-labs/ERC721A-Upgradeable#5]
Hi Chiru Labs.
Thanks for sharing this upgradeable version of ERC721A.
I just installed the latest version and getting one issue while compiling the contracts.
```
  --> erc721a-upgradeable/contracts/ERC721AUpgradeable.sol:92:82:
   |
92 |     function __ERC721A_init(string memory name_, string memory symbol_) internal onlyInitializing {
   |    
```
I can't find `onlyInitializing` modifier from anywhere.
Can you pls help me?

**Comment by Vectorized** [comment]
Are you using hardhat?

The `onlyInitializing` modifer comes from OpenZeppelin's Upgradeable repo  
(which is already added as a dependency in ERC721A-Upgradeable's `package.json`)

See https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/proxy/utils/Initializable.sol

**Comment by gmspacex** [comment]
Thanks, I just upgraded the openzeppelin version to the latest one and it is resolved.
