### ISSUE TITLE
ERC721A Upgradeable v3.3.0 Update

### ISSUE THREAD

**Issue by kyokosdream** [chiru-labs/ERC721A-Upgradeable#8]
In the most recent update for ERC721A (v3.3.0) the upgradeable version of the contract now has a constructor instead of an initializer function. Was this intended? 

In addition the Upgradeable suffix has been removed from the contracts. I believe this may be a mistake.

**Comment by Vectorized** [comment]
Oh dang, OZ updated their transpiler.

The files on npm are still the same.

**Comment by Vectorized** [comment]
@kyokosdream Fixed. The most recent PR on the main repo cause the transpiler to break. Just made another PR to fix it.

The npm files were still valid, as they are only updated on version release.
